stages:
  - build
  - deploy

variables:
  GIT_DEPTH: "1"

build:
  stage: build
  tags: 
    - linux
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - dist/

deploy_npm:
  stage: deploy
  dependencies:
    - build
  tags:
    - linux
  script:
    - apt update;apt -y install coreutils
    - echo $NPMRC | base64 --decode > ~/.npmrc
    - npm publish . || true
  only:
    - master
